### ISSUE TITLE
Tidy up csproj

### ISSUE THREAD

**Issue by WiredUK** [Comentsys/Comentsys.Assets.FluentEmoji#2]
I may be wrong but.... I think you can remove all of these:

    <EmbeddedResource Include="Resources\Flat\FirstPlaceMedal.svg" />

From your csproj file and replace them with wildcards:

    <EmbeddedResource Include="Resources\Flat\*.svg" />

**Comment by RoguePlanetoid** [comment]
I totally forgot that was a thing, there was a helper app I used to process the Emoji and just had it output those elements too, but that's a lot cleaner in the csproj. I'll get those updated
